'use client'

import { useState } from 'react'
import { Sparkles } from 'lucide-react'

export default function RecipeSection() {
  const [showRecipeModal, setShowRecipeModal] = useState(false)

  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-6 text-center">
        <h2 className="text-4xl font-playfair text-center mb-6 text-green-800">
          Discover Delicious Recipes
        </h2>
        <p className="text-gray-600 max-w-2xl mx-auto mb-8">
          Unlock the culinary potential of Sithaphal with unique recipes generated by AI. 
          From smoothies to desserts, find your next favorite dish.
        </p>
        <button 
          onClick={() => setShowRecipeModal(true)}
          className="btn-primary px-8 py-4 rounded-lg text-lg font-semibold flex items-center space-x-2 mx-auto hover:scale-105 transition-transform"
        >
          <Sparkles className="w-5 h-5" />
          <span>Generate Recipes</span>
        </button>
      </div>
    </section>
  )
}
